apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:marcelvanleeuwen/homelab-gitops.git
    targetRevision: main
    path: clusters/production/metallb

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
